language: python
python:
  - "3.7"
install:
  - pip install coveralls
  - python setup.py install
script:
  - python -m unittest
  - coverage run --source epsonprojector setup.py test

after_success:
    coveralls


deploy:
  provider: pypi
  user: $username
  password: $password
  on:
    branch: release
