$schema: http://json-schema.org/draft-07/schema#
type: object
title: Projector Configuration Schema
additionalProperties: false
required:
- commands
properties:
  commands:
    $id: '#/properties/commands'
    type: array
    items: { "$ref": "#/definitions/command" }
    uniqueItems: true
    minItems: 1
    title: Command List
    required:
    - command
definitions:
  parameter:
    type: object
    title: Parameter
    properties:
      parameter:
        type: string
        description: Machine Value
      name:
        type: string
        description: Alternative Code Value
        pattern: ^([\w_-])+$
      display_name:
        type: string
        description: Human readable Value

  command:
    type: object
    title: Command
    required:
    - command
    - request_parameters
    - response_parameters
    properties:
      command:
        type: string
        title: Slug
        description: Slug for Command
      name:
        type: string
        title: command
        description: Command to send to a projector
        pattern: ^([\w_-])+$
      display_name:
        type: string
        title: Display Name
        description: User friendly Name of Command
      request_parameters:
        type: array
        title: Request Parameters
        description: This Parameters can be send to Device
        items: { "$ref": "#/definitions/parameter" }
      response_parameters:
        type: array
        title: Response Parameters
        description: The Response_parameters Schema
        items: { "$ref": "#/definitions/parameter" }
